import React, { Component } from 'react';
import { connect } from 'react-redux';
import {selectBook} from '../actions/index';
// function to make sure all our actions generated by action creators flows through the different reducers in our app.
import { bindActionCreators } from 'redux';

class BookList extends Component {
  renderList() {
    return this.props.books.map((book) => {
      return (
        <li
          key={book.title}
          onClick={() => this.props.selectBook(book)}
          className="list-group-item">
          {book.title}
        </li>
      );
    });
  }

  render() {
    return (
      <ul className="list-group col-sm-4">
        { this.renderList() }
      </ul>
    )
  }
}

//whatever object is returned will be available to our component as this.props
//glue between react and redux
function mapStateToProps(state) {
  //Whatever is returned will show up as props inside of BookList
  return {
    books: state.books
  }
}
// whenever our state changes, 
// this container will instantly re-render with a
// new list of books.

//Anything returned from this function, will end up as props
//on the BookList container
function mapDispatchToProps(dispatch) {
//whenever selectBook is called, results should be passed
//to all our reducers
  return bindActionCreators({ selectBook: selectBook }, dispatch)
}

// Promote BookList from a component to a container - 
// it needs to know about this new dispatch method, selectBook.
// Make it available as a prop.
export default connect(mapStateToProps, mapDispatchToProps)(BookList);
// At top we import connect from react-redux
// This is where the merge between react and redux comes
// connect takes a function and a component as an argument
// this will produce a container
